config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'ordens' => 'ordenes#new'
  post 'ordens' => 'ordenes#new'

  get 'usuarios/new'

  root 'estaticas#home'

  get 'cotiza' => 'estaticas#cotiza'

  get 'unete' => 'estaticas#unete'

  get 'acercade' => 'estaticas#acercade'

  get 'faq' => 'estaticas#faq'

  get 'politicas' => 'estaticas#politicas'

  get 'contacto' => 'estaticas#contacto'

  get 'privacidad' => 'estaticas#privacidad'

  get 'nuevacuenta' => 'usuarios#nueva'

  get 'trazaruta' => 'estaticas#rutas'

  resources :usuarios
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :ordenes

  match '/cotizacion',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  match '/pides', to: 'pides#new', via: 'get'
  resources "pides", only: [:new, :create]

end

app/views/layouts/_footer.html.erb
<footer id="footer">
          <ul class="menu-footer">
            <li><h4><%= link_to "Acerca de nosotros", acercade_path %></h4></li>
            <li><h4><%= link_to "Contacto", contacto_path %></h4></li>
            <li><h4><%= link_to "Aviso de privacidad", privacidad_path %></h4></li>
          </ul>
          <ul class="icons">
            <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
          </ul>
          <ul class="copyright">
            <li>&copy;. Todos los derechos reservados.</li><li> <a href="#">#bisonteDeOro</a></li>
          </ul>
          <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3AVY2thZrxj2xtZbwcSnJdliHJZkIfty";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->
</footer>

app/views/layouts/_header.html.erb
<header id="header" class="navbar navbar-fixed-top navbar-inverse alt">

	<h1 style="margin-top: 6px;">
		<%= link_to root_path do %>
		   <%= image_tag 'logo-bicimensajero.png', width: 200, alt: 'Bicimensajero' %>
		<% end %>
	</h1>  

    <nav id="nav">
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Cotiza", pides_path, 'data-no-turbolink' => true, :class => 'button buttonGrande' %></li>

      	<!--

      	<% if logged_in? %>
      	<li><%= link_to "Usuarios", usuarios_path %></li>
      	<li><%= link_to "Cerrar sesión", logout_path, method: "delete" %></li>
      	<li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	          Mi cuenta <b class="caret"></b>
	        </a>
	        <ul class="dropdown-menu">
	          <li><%= link_to "Perfil", current_usuario %></li>
	          <li><%= link_to "Ajustes de mi cuenta", edit_usuario_path(current_usuario) %></li>
	          <li class="divider"></li>
	          <li>
	            <%= link_to "Cerrar sesión", logout_path, method: "delete" %>
	          </li>
	        </ul>
	     </li>
	    <% else %>
      	<li><%= link_to "Crea una cuenta", nuevacuenta_path, id: "login", :class => 'button' %></li>
        <li><%= link_to "Ingresa a tu cuenta", login_path, id: "login", :class => 'button' %></li>
        <% end %>

    	-->

      </ul>
    </nav>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title><%= yield(:title) %>Bicimensajero</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>
<body class="landing" data-no-turbolink="true">

        <div id="page-wrapper">
          <%= render 'layouts/header' %>
        </div>
      


    <!--Mostrar Terminal-->
    <div class="margenTop">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>

    </div>

</body>
</html>